[package]
name = "agents"
version = "0.0.1"
edition = "2021"

[dependencies]
burn = { version = "0.14.0", features = ["train", "wgpu", "vision"] }
gym-rs = "0.3.0"
ordered-float = "4.3.0"
rand = "0.8.5"
